In [6]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2])
print(type(arr))

3
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr=np.array((1,2,3,4))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4]


In [11]:
#O-D Array
import numpy as np
arr=np.array(42)
print (arr)

42


In [12]:
#1-D Array
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [14]:
#2-D Array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
#3-D Array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
#check dimension of the array
import numpy as np
a=np.array(42)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [19]:
#Higher Dimension
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('Number of Dimension :',arr.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimension : 5


In [22]:
#Accessing Array Element
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[2])
#add 3rd and 4th elements and add them
print(arr[2]+arr[3])

1
3
7


In [25]:
#Access 2-D Array
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim : ',arr[0,1])

2nd element on 1st dim :  2


In [27]:
#Access 5th element of the 2nd dim
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element of the 2nd dim :',arr[1,4])


5th element of the 2nd dim : 10


In [29]:
#Access 3-D Array
#access the third element of the second array of the first array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [33]:
#Negative Indexing access array from the end
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim :',arr[1,-1])

Last element from 2nd dim : 10


In [34]:
sam=np.array("sameera")
print(sam)

sameera


In [2]:
#NumPy Array Slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [3]:
#Slice elements from index 4 to the end of the array
print(arr[4:])

[5 6 7 8 9]


In [4]:
#Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[1 2 3 4]


In [5]:
#Negative Slicing
#Use the minus operator to refer to an index from the end
print(arr[-3:-1])

[7 8]


In [6]:
#STEP
#Use the step value to determine the step of the slicing
print(arr[1:5:2])

[2 4]


In [8]:
#Return every other element from the entire array
print(arr[::2])

[1 3 5 7 9]


In [23]:
import numpy as np

import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1, 1:3])


[5 6]
